<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>iTunesRPC</AssemblyName>
    <RootNamespace>iTunesRPC</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>
